name: generate animation

on:
  # run automatically every 24 hours
  schedule:
    - cron: "0 */8 * * *"

  # Allows manual triggering of the workflow via the GitHub UI
  workflow_dispatch:

  push: # Trigger the workflow when changes are pushed
    branches:
      - main # Trigger only when changes are pushed to the main branch

jobs:
  generate-animation:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}

          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: push github-contribution-grid-snake.svg to the commit-snake branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: commit-snake
          build_dir: dist
          commit_message: Update GitHub contribution commit snake animation
        env:
          # This token is automatically provided by GitHub Actions
          # and is necessary to push changes to the repository
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
